program: tictactoe.o tictactoe_function.o
		gcc -o TicTacToe	tictactoe.o tictactoe_function.o

tictactoe.o: tictactoe.c tictactoe.h
		gcc -c tictactoe.c

tictactoe_function.o: tictactoe_function.c tictactoe.h
		gcc -c tictactoe_function.c
